### ISSUE TITLE
Experiment with building ESMF with gcc13

### ISSUE THREAD

**Issue by oehmke** [esmf-org/esmf#235]
A user (Gabor Toth) had some issues building with it, so it would be good to test it out and fix any that come up (especially before the next release).

**Comment by mathomp4** [comment]
@oehmke As a data point, we (GMAO) have had no issues so far with ESMF + GCC 13. It's all been in other layers.

**Comment by anntsay** [comment]
Matt from NASA said it was ok.. but need to try within ESMF.  Next step is to switch one machine to gcc13 to test this.   

Ufuk: should we test this in Speck?

Action:  Ufuk will fire up a test in Speck because it has gcc13.1.0.  https://github.com/esmf-org/esmf/actions/runs/8820187543
  Bob, will look for an older GGC to switch to GGC13

**Comment by uturuncoglu** [comment]
@anntsay @oehmke JFYI, It seems that the action was completed without any issue and all NUOPC app prototypes are passed with gcc 13.1.0.

**Comment by oehmke** [comment]
Great! Thanks for doing that. It’s nice to know that there aren’t any issues in this case. Before next release, I’ll switch a case or two to test this, so that we can keep an eye on it as we develop for 8.7.

**Comment by mathomp4** [comment]
Indeed, because MAPL (and thus GEOSgcm) now support GCC 13, I've moved all our CI and test runs for GEOSgcm and MAPL to GCC 13.2.

(Now to wait for the inevitable change that breaks GCC 12... 😄 )

**Comment by anntsay** [comment]
Ufuk:  it is also working with gcc14 this is because the action was picking the latest gcc.
