### ISSUE TITLE
Install FindESMF.cmake into <ESMF_INSTALL_PREFIX>/cmake

### ISSUE THREAD

**Issue by danrosen25** [esmf-org/esmf#279]
During the `make install` step provide `FindESMF.cmake` into the installation of ESMF under a `<ESMF_INSTALL_PREFIX>/cmake` directory.

Yes, I realize this is strange because FindESMF.cmake is intended to find the ESMF_INSTALL_PREFIX location given ESMF_ROOT or ESMFMKFILE as hints.

**Comment by danrosen25** [comment]
@theurich - Do you have any thoughts on this before I proceed?

**Comment by theurich** [comment]
It is strange, and previously when this has come up, I always recommended not doing it. 
However, I am starting to realize that in practice people might expect to find `FindESMF.cmake` within the ESMF installation. Those people might not go look for it on GitHub to find it under the ESMF repo (which is actually where they should get it). So I am fine with this going under the installation dir, inside a `cmake` directory now, in order to help out those folks that go look for it there.
Maybe we should also put a `README` file inside of the `cmake` dir under the installation dir, where we explain how the `FindESMF.cmake` is intended to be used. I.e. it is an example of a `FindESMF.cmake`, which a user would use in their own project by copying it to their own project and use it from there. They might need to make modifications on their own version if it isn't exactly what they need it to do, but it should be a good starting point.

**Comment by danrosen25** [comment]
@theurich 
What do you think of this documentation?
https://github.com/danrosen25/esmf/tree/feature/install_cmake/cmake
I'll bring this branch over to esmf-org once edits are complete. Then I can put it on the project board to integrate this into develop for 8.8.0
