### ISSUE TITLE
Timemgr using sprintf with the output string also used in the input

### ISSUE THREAD

**Issue by oehmke** [esmf-org/esmf#284]
Atanas  ran into an issue with a garbled time string and traced it down to a sprintf call in the time manager. It looks like there are several instances of sprintf() with the output string being also used as an input. It sounds like in general this shouldn't be done, but that it sometimes works (depending on the implementation of sprintf()). We should fix all of these, so we don't run into random issues. An example of one of these is in .../TimeMgr/src/ESMCI_Time.C line 1482.

**Comment by billsacks** [comment]
I'm happy to take this on.

I just did a regex search to try to identify the places that need to be fixed. This would miss anything where a sprintf call is split across multiple lines, but hopefully is at least a good start: The regex is `sprintf *\(([^,]+) *,.*\1`. There are a number of false positives, but it picks up some things that should be fixed:

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/Mesh/src/Legacy/ESMCI_MeshMerge.C#L1183

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/Mesh/src/Legacy/ESMCI_MeshMerge.C#L1186

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L1471

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L1473

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L1480

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L1482

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_TimeInterval.C#L3142

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_TimeInterval.C#L3144

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_TimeInterval.C#L3151

https://github.com/esmf-org/esmf/blob/82f8052f9cfee57e81a2c7a74e5dfa05870b7b93/src/Infrastructure/TimeMgr/src/ESMCI_TimeInterval.C#L3153

**Comment by oehmke** [comment]
Thanks Bill! Nice regex. :-)  If it’s not hard, while you’re in there, you could think about switching to snprintf(), since sprintf() is deprecated (it is vulnerable to buffer overflows).

**Comment by billsacks** [comment]
I've started looking at this. @oehmke I'd like some confirmation on what I'm thinking here:

I'm thinking that, ideally, we should add an argument to these two functions:

https://github.com/esmf-org/esmf/blob/edb848d90bf5d70a2db158771f4d07be605fdd32/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L1390-L1396

https://github.com/esmf-org/esmf/blob/edb848d90bf5d70a2db158771f4d07be605fdd32/src/Infrastructure/TimeMgr/src/ESMCI_TimeInterval.C#L3072-L3078

giving the string length. It looks to me like we have that length available in all calls; for example:

https://github.com/esmf-org/esmf/blob/edb848d90bf5d70a2db158771f4d07be605fdd32/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L433

which is referenced here:

https://github.com/esmf-org/esmf/blob/edb848d90bf5d70a2db158771f4d07be605fdd32/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L547-L548

But I'm not familiar enough with the Fortran-C connections in ESMF to be confident about this: **can we rely on this timeStringLen variable being the size of the C character allocation for tempTimeString? Or maybe off-by-one because of the need to hold the terminating null character on the C side??** In case it's helpful, this is the relevant Fortran-C call:

https://github.com/esmf-org/esmf/blob/edb848d90bf5d70a2db158771f4d07be605fdd32/src/Infrastructure/TimeMgr/interface/ESMCI_Time_F.C#L91-L161

My sense is that these `getString` methods are only accessible internally, so it's okay to change the interface... `Time::getString` is a public method and appears like this:

https://github.com/esmf-org/esmf/blob/edb848d90bf5d70a2db158771f4d07be605fdd32/src/Infrastructure/TimeMgr/src/ESMCI_Time.C#L1381-L1390

but my impression is that this C++ code isn't actually part of the ESMF public API; is that true?

Let me know if you'd find it easier to meet to talk about this rather than trying to reply in writing. I have other things I can work on while waiting for a reply, so no rush on this. (I thought maybe if I got this done quickly I could sneak this bug fix into 8.7, but that may be unrealistic at this point.)

**Comment by mathomp4** [comment]
Just a note. We had another user on Linux 6.8+ (@gmao-ckung) hit this, so it might become more prevalent!

Thanks for looking at this!

**Comment by oehmke** [comment]
Hi Bill,

  Yes, that makes sense to add the argument with the string length. We trust that Fortran length other places in the code and we don’t seem to have issues with it, so I think it’s ok to use. I think that it’s just the length without the null terminator, but I’ll have to look a bit to be sure. We have some interface functions to help with the F to C strings, but I’ll have to remind myself about how it works (I don’t do it super often), but I can find some examples for you to use. 

  Are you in T or Th next week? How about we meet to talk about it and look at some code? That’ll give me time to swap it back into main memory. ;-)

- Bob
