### ISSUE TITLE
Typo in many build_rules.mk files for identifying ESMF_LIBGFORTRAN

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#73]
I noticed that many of the build_rules.mk files have a block like this:

https://github.com/esmf-org/esmf/blob/fa383530e09d1a016c13b447f5fc4b1bf7283fba/build_config/Linux.gfortran.default/build_rules.mk#L273-L276

I'm thinking that the reference to ESMF_LIBSTDCXX on line 274 should actually refer to ESMF_LIBGFORTRAN. Do others agree?

**Comment by theurich** [comment]
I do agree that this looks like a copy-and-paste issue from the CXX block just before and should be corrected.

Also it looks to me that the logic should in both cases be `ifneq()`, i.e. only look for the static library if the shared library was NOT found. Most of the time this will not be an issue, because both libs are there, and also for that reason even the STDCXX vs GFORTRAN mix up did not matter, but it should be fixed right.

Very nice to have someone work though this stuff with a fine tooth comb!

**Comment by billsacks** [comment]
Thanks, @theurich . I can take this on, but I'll probably separate it from the clang work I'm doing to avoid confusion.

If I understand what this is supposed to be doing, I think the `ifeq` logic is correct, even though it's not intuitive: The result of `gfortran -print-file-name=libgfortran.so` is the full path to `libgfortran.so` if it's found, or simply "libgfortran.so" if not. For example, on my system that has libgfortran.dylib but not libgfortran.so:

```
$ gfortran -print-file-name=libgfortran.dylib
/opt/homebrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin21/12/../../../libgfortran.dylib
$ gfortran -print-file-name=libgfortran.so
libgfortran.so
```

So it looks like the `ifeq` will actually trigger if the shared library was not found.

**Comment by theurich** [comment]
Yes, good point about the logic, it is correct, I agree!

When you fix this, could you please add a one line comment saying that -print-file-name will echo the file verbatim if it is NOT found, but will prepend the full path if it is found within the GCC installation.?

I am sure I personally added those ifeq() years ago, and my own confusion now shows that I should have added a comment about this counter intuitive behavior.

Thanks!
