### ISSUE TITLE
NetCDF paths not being picked up properly on Macs with the latest NetCDF from homebrew due to logic in nfconfigtest

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#81]
With the latest version of NetCDF through homebrew on a Mac, the Fortran includes and libs no longer seem to be bundled with the standard netcdf package. Instead, I needed to install them separately via `brew install netcdf-fortran`. This leads to the Fortran includes and libs being in a different directory from the C includes and libs. nf-config or nc-config can properly tell you about this, but this currently isn't working in an ESMF build with `export ESMF_NETCDF=nc-config` (and so we end up with just the C includes and libs, not the Fortran ones, leading to `Fatal Error: Cannot open module file 'netcdf.mod' for reading`).

The issue seems to be that the script `nfconfigtest` is returning "notworking" even though I have a functional nf-config. That script expects `nf-config --version` to return a string that starts with "netCDF-Fortran", but in the current version of netcdf-fortran through homebrew, `nf-config --version` just gives "4.6.0-development".

@theurich it looks like you added the nfconfigtest script a few years ago, in 8da808d20c. This seems to be trying to detect the possibility that `nf-config` is in your path but somehow broken. Do you remember the details that required you to create this, and do you think we can come up with a different way to detect this situation?

**Comment by theurich** [comment]
@billsacks, this was needed for an issue that Ufuk ran into. It was tracked under the old SF tracker: https://sourceforge.net/p/esmf/tix/3614881/ (let me know if you cannot access it, and I can add your SF id to the old tracker).

Bottom line was that Ufuk reported the issue below. Commit 8da808d20c fixed it for him.

--

Hi All,

If i set
export ESMF_NETCDF=nc-config
it relies on having working nf-config command but if i use netcdf compiled with cmake, i am getting following error with 8.0.0
/work/01118/tg803972/stampede2/UFS/ESMF/8.0.0/build/common.mk:1383: *** invalid syntax in conditional. Stop.
This is because if you install netcdf with cmake, and try to run

nf-config --prefix
command it gives

nf-config not yet implemented for cmake builds
error but nc-config works fine. So, i am not sure this is a bug in ESMF build system but the build system could use nc-config instead of nf-config if nf-config does not return anything valuable for ESMF.

Regards,

--ufuk

**Comment by billsacks** [comment]
I don't have access to the sourceforge esmf tickets. If it's easy for you to add me, my user name on sourceforge is wsacks.

I'd like to try to get this working for the latest Mac / homebrew netcdf situation. I can see three possible paths forward, from easiest to hardest, but possibly also from least to most robust:

(1) Remove this nfconfigtest logic, because according to recent comments in https://github.com/Unidata/netcdf-fortran/issues/60 this should be working for the last 2.5 years (despite that issue not being closed)

(2) Try to change nfconfigtest so that it gives "working" for the Mac situation but still gives "notworking" for @uturuncoglu 's original situation (maybe by searching for "not yet implemented" in the output?)

(3) Add more logic to common.mk so that the fallback to nc-config works more robustly: currently it seems like this fallback is partially working, but not well enough.

Do you have thoughts on the best path?

**Comment by theurich** [comment]
@billsacks - I just added you to the ESMF project under SF. Obviously we are not using that infrastructure anymore, but just in case there are other tickets we might reference back to in the future. There is not a whole lot of additional info under this specific ticket though.

I haven't looked at the details, but from what you are writing, solution (2) seems like a good next step to me. But I am also fine with (3), I just don't have my head into this enough right now to know what that would mean. My only concern with some major work in common.mk is that we are close to freezing for 8.4.0, and so it might not be the best time to do it. So if (2) gets us a working clang configuration with netcdf on your Mac, then it might be safer.
As soon as we cut the release branch, I have no objections to more substantial changes under common.mk to address the NetCDF issue.

**Comment by billsacks** [comment]
I implemented solution (2) in 2dc24cd75c. This issue will be closed when #79 is merged.
