### ISSUE TITLE
Pthreads support under Darwin.gfortranclang.default

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf#87]
Currently `build_config/Darwin.gfortranclang.default/build_rules.mk` contains this section
```
  ############################################################
  # Gfortran runtime library on Darwin does not currently seem thread-safe
  #
  ESMF_PTHREADS := OFF
```
I am hoping that this is outdated, and can be removed. We have it already removed under `build_config/Darwin.gfortran.default/build_rules.mk`.
This needs to be tested under a new feature branch. We need runs for the 3 Darwin.gfortranclang combos that Bill has set up under his M1. If testing looks good, then this should make it into release 8.4.0.

**Comment by billsacks** [comment]
Thanks, @theurich ! You're right that it appears to work to remove that section. I first ran the ESMF tests with TESTEXHAUSTIVE with openmpi-g and all still pass except for the one test that has been failing. Then I ran the nuopc app prototype tests manually. I wasn't 100% sure how to do this, but I simply exported ESMFMKFILE then ran `testProtos.sh`. The tests that failed before due to pthreads issues now pass. There are still build failures in AtmOcnSelectExternalProto. However, ESMX_AtmOcnProto hung: I let it go for 20 minutes then killed it. I'm thinking that hang will be a problem for testing. Do you want me to investigate it?

**Comment by theurich** [comment]
That all sounds very good. For now you can use branch `fix/catania` under the NUOPC app protos repo to get around the hanging. This issue under Darwin is being tacked as https://github.com/esmf-org/esmf/issues/89, and I am planning on taking a look at it today. I am hopeful it can be sorted out for 8.4.0.

With the results you already have, I'd say to go ahead and push the change wrt Pthreads support under Darwin.gfortranclang.default/build_rules.mk into develop.

**Comment by billsacks** [comment]
Thanks @theurich . I just merged this. I'll kick off a new round of testing on green with these changes (enable pthreads, use fix/catania nuopc branch) to update the test page with these results.
