### ISSUE TITLE
ESMF_ArrayRedistSharedObjSTest fails on systems with shared obj extensions different from .so (e.g., Darwin)

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf#90]
When running 'make all_tests' with ESMF_TESTSHAREDOBJ=ON, ESMF_ArrayRedistSharedObjSTest is failing on my Mac (i.e., Darwin system) because ESMF_ArrayRedistSharedObjSTest.F90 assumes that shared libraries have a ".so" extension, whereas Darwin systems use ".dylib".

I started down the path of making this more dynamic by adding this to the relevant makefile:
```diff
diff --git a/src/system_tests/ESMF_ArrayRedistSharedObj/makefile b/src/system_tests/ESMF_ArrayRedistSharedObj/makefile
index da3042967a..661e6c0656 100644
--- a/src/system_tests/ESMF_ArrayRedistSharedObj/makefile
+++ b/src/system_tests/ESMF_ArrayRedistSharedObj/makefile
@@ -12,6 +12,7 @@ LOCDIR          = src/system_tests/ESMF_ArrayRedistSharedObj


 ifeq ($(ESMF_TESTSHAREDOBJ),ON)
+ESMF_CPPFLAGS += -DESMF_SL_SUFFIX=$(ESMF_SL_SUFFIX)
 SYSTEM_TESTS_BUILD    = $(ESMF_TESTDIR)/ESMF_ArrayRedistSharedObjSTest
 SYSTEM_TESTS_RUN      = RUN_ArrayRedistSharedObj
 else
```

and then hoping to use the defined value of ESMF_SL_SUFFIX in place of the hard-coded ".so" in ESMF_ArrayRedistSharedObjSTest.F90. However, the only way I can see to do this is to use preprocessor macros like those defined here:
https://github.com/esmf-org/esmf/blob/c2de0893c179f4cf9563a51436af85b43b519726/src/Superstructure/ESMFMod/interface/ESMCI_Init_F.C#L46-L48

and those don't seem to work with gfortran's preprocessor.

I guess I could call into a little C function to get a string value of this CPP macro, but this is starting to feel pretty complex, and I'm wondering if anyone has a simpler idea for how to do this. If nobody has a simpler idea, then I can go down this path of calling into C to get the string value of ESMF_SL_SUFFIX and using that in place of the hard-coded ".so".

Or should we simply not worry about this test passing on systems that use an extension other than ".so"?

**Comment by theurich** [comment]
A simpler solution here might just be to add logic like the following into `src/system_tests/ESMF_ArrayRedistSharedObj/ESMF_ArrayRedistSharedObjSTest.F90`:
```
#ifdef ESMF_OS_Darwin
sharedObj="./user_model1.dylib"
#else
sharedObj="./user_model1.so"
#endif
```
I know this is less flexible, than the direction you were going down, but in reality we are really only dealing with Dawin being a special case here wrt the suffix. Maybe also Cygwin if we ever need to really get that into shape, but even then it's three options here and very simple code that deals with it.
BTW, I also saw the issue under Catania, but since we are not setting ESMF_TESTSHAREDOBJ=ON anywhere right now I turned a blind eye toward it. If we go with the simple solution, I think this could go in before the branch cut.

**Comment by billsacks** [comment]
Thanks @theurich . I just pushed a solution similar to the one you suggested and confirmed that it fixes this test case on my Mac. (I haven't tried it elsewhere.)

**Comment by theurich** [comment]
@billsacks, this looks good to me. I tested it on Catania, and it works there as well with ESMF_TESTSHAREDOBJ=ON. Nice to have this done for when we start testing with this option across the platforms.
